version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    target-branch: "master"
    commit-message:
      prefix: "build(deps)"
    labels:
      - "dependencies"
      - "android"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    target-branch: "master"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
